/*
 * Copyright (C) 2014 410134
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package cz.fi.muni.pv097.Gui.SideBars;

import cz.fi.muni.pv097.Canvases.ImageGeneratorPreview;
import cz.fi.muni.pv097.CoreComponents.AbstractFiller;

/**
 *
 * @author 410134
 */
public class ManualSideBar extends javax.swing.JPanel {

    private final ImageGeneratorPreview canvas;
    private final AbstractFiller alg;

    /**
     * Creates side bar for control
     *
     * @param pr drawing canvas
     * @param alg algorithm
     */
    public ManualSideBar(ImageGeneratorPreview pr, AbstractFiller alg) {
        super();
        initComponents();
        canvas = pr;
        this.alg = alg;
    }

    /**
     *
     * @return state of gavitation
     */
    public boolean getGravity() {
        return this.gravitationToggleButton.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NextPartjButton = new javax.swing.JButton();
        Up = new javax.swing.JButton();
        Right = new javax.swing.JButton();
        Left = new javax.swing.JButton();
        Down = new javax.swing.JButton();
        LRotationjButton = new javax.swing.JButton();
        RRotationjButton = new javax.swing.JButton();
        gravitationToggleButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(176, 450));
        setMinimumSize(new java.awt.Dimension(176, 450));
        setOpaque(false);
        setLayout(null);

        NextPartjButton.setText("Add next part");
        NextPartjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextPartjButtonActionPerformed(evt);
            }
        });
        add(NextPartjButton);
        NextPartjButton.setBounds(10, 90, 130, 23);

        Up.setText("Up");
        Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpActionPerformed(evt);
            }
        });
        add(Up);
        Up.setBounds(40, 160, 61, 23);

        Right.setText("Right");
        Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightActionPerformed(evt);
            }
        });
        add(Right);
        Right.setBounds(80, 190, 59, 23);

        Left.setText("Left");
        Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftActionPerformed(evt);
            }
        });
        add(Left);
        Left.setBounds(10, 190, 59, 23);

        Down.setText("Down");
        Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownActionPerformed(evt);
            }
        });
        add(Down);
        Down.setBounds(40, 220, 61, 23);

        LRotationjButton.setText("L");
        LRotationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LRotationjButtonActionPerformed(evt);
            }
        });
        add(LRotationjButton);
        LRotationjButton.setBounds(10, 280, 40, 23);

        RRotationjButton.setText("R");
        RRotationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRotationjButtonActionPerformed(evt);
            }
        });
        add(RRotationjButton);
        RRotationjButton.setBounds(100, 280, 41, 23);

        gravitationToggleButton.setText("Gravitation");
        gravitationToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gravitationToggleButtonItemStateChanged(evt);
            }
        });
        add(gravitationToggleButton);
        gravitationToggleButton.setBounds(30, 50, 85, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Moves:");
        add(jLabel1);
        jLabel1.setBounds(30, 130, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rotations:");
        add(jLabel2);
        jLabel2.setBounds(30, 250, 80, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void NextPartjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextPartjButtonActionPerformed
        canvas.addPart();
        canvas.repaint();
    }//GEN-LAST:event_NextPartjButtonActionPerformed

    private void UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpActionPerformed
        canvas.move(-2);
        canvas.repaint();
    }//GEN-LAST:event_UpActionPerformed

    private void RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightActionPerformed
        canvas.move(1);
        canvas.repaint();
    }//GEN-LAST:event_RightActionPerformed

    private void LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftActionPerformed
        canvas.move(-1);
        canvas.repaint();
    }//GEN-LAST:event_LeftActionPerformed

    private void DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownActionPerformed
        canvas.move(2);
        canvas.repaint();
    }//GEN-LAST:event_DownActionPerformed

    private void LRotationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LRotationjButtonActionPerformed
        canvas.rotateLeft();
        canvas.repaint();
    }//GEN-LAST:event_LRotationjButtonActionPerformed

    private void RRotationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRotationjButtonActionPerformed
        canvas.rotateRight();
        canvas.repaint();
    }//GEN-LAST:event_RRotationjButtonActionPerformed

    private void gravitationToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gravitationToggleButtonItemStateChanged
        if (gravitationToggleButton.isSelected()) {
            alg.compute();
        } else {
            alg.stop();
        }
    }//GEN-LAST:event_gravitationToggleButtonItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Down;
    private javax.swing.JButton LRotationjButton;
    private javax.swing.JButton Left;
    private javax.swing.JButton NextPartjButton;
    private javax.swing.JButton RRotationjButton;
    private javax.swing.JButton Right;
    private javax.swing.JButton Up;
    private javax.swing.JToggleButton gravitationToggleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
